INSERT INTO Srd521MonsterCr (name, cr) VALUES
      ('Aboleth', '10'),
      ('Air Elemental', '5'),
      ('Animated Armor', '1'),
      ('Animated Rug of Smothering', '2'),
      ('Ankheg', '2'),
      ('Assassin', '8'),
      ('Awakened Tree', '2'),
      ('Azer Sentinel', '2'),
      ('Balor', '19'),
      ('Bandit Captain', '2'),
      ('Barbed Devil', '5'),
      ('Basilisk', '3'),
      ('Bearded Devil', '3'),
      ('Behir', '11'),
      ('Berserker', '2'),
      ('Black Dragon Wyrmling', '2'),
      ('Young Black Dragon', '7'),
      ('Adult Black Dragon', '14'),
      ('Ancient Black Dragon', '21'),
      ('Black Pudding', '4'),
      ('Blue Dragon Wyrmling', '3'),
      ('Young Blue Dragon', '9'),
      ('Adult Blue Dragon', '16'),
      ('Ancient Blue Dragon', '23'),
      ('Bone Devil', '9'),
      ('Brass Dragon Wyrmling', '1'),
      ('Young Brass Dragon', '6'),
      ('Adult Brass Dragon', '13'),
      ('Ancient Brass Dragon', '20'),
      ('Bronze Dragon Wyrmling', '2'),
      ('Young Bronze Dragon', '8'),
      ('Adult Bronze Dragon', '15'),
      ('Ancient Bronze Dragon', '22'),
      ('Bugbear Stalker', '3'),
      ('Bugbear Warrior', '1'),
      ('Bulette', '5'),
      ('Centaur Trooper', '2'),
      ('Chain Devil', '8'),
      ('Chimera', '6'),
      ('Chuul', '4'),
      ('Clay Golem', '9'),
      ('Cloaker', '8'),
      ('Cloud Giant', '9'),
      ('Copper Dragon Wyrmling', '1'),
      ('Young Copper Dragon', '7'),
      ('Adult Copper Dragon', '14'),
      ('Ancient Copper Dragon', '21'),
      ('Couatl', '4'),
      ('Swarm of Crawling Claws', '3'),
      ('Cultist Fanatic', '2'),
      ('Death Dog', '1'),
      ('Deva', '10'),
      ('Djinni', '11'),
      ('Doppelganger', '3'),
      ('Dragon Turtle', '17'),
      ('Drider', '6'),
      ('Druid', '2'),
      ('Dryad', '1'),
      ('Earth Elemental', '5'),
      ('Efreeti', '11'),
      ('Erinyes', '12'),
      ('Ettercap', '2'),
      ('Ettin', '4'),
      ('Fire Elemental', '5'),
      ('Fire Giant', '9'),
      ('Flesh Golem', '5'),
      ('Frost Giant', '8'),
      ('Gargoyle', '2'),
      ('Gelatinous Cube', '2'),
      ('Ghast', '2'),
      ('Ghost', '4'),
      ('Ghoul', '1'),
      ('Giant Ape', '7'),
      ('Giant Boar', '2'),
      ('Giant Constrictor Snake', '2'),
      ('Giant Crocodile', '5'),
      ('Giant Eagle', '1'),
      ('Giant Elk', '2'),
      ('Giant Hyena', '1'),
      ('Giant Octopus', '1'),
      ('Giant Scorpion', '3'),
      ('Giant Shark', '5'),
      ('Giant Spider', '1'),
      ('Giant Toad', '1'),
      ('Giant Vulture', '1'),
      ('Gibbering Mouther', '2'),
      ('Glabrezu', '9'),
      ('Gladiator', '5'),
      ('Goblin Boss', '1'),
      ('Gold Dragon Wyrmling', '3'),
      ('Young Gold Dragon', '10'),
      ('Adult Gold Dragon', '17'),
      ('Ancient Gold Dragon', '24'),
      ('Gorgon', '5'),
      ('Green Dragon Wyrmling', '2'),
      ('Young Green Dragon', '8'),
      ('Adult Green Dragon', '15'),
      ('Ancient Green Dragon', '22'),
      ('Green Hag', '3'),
      ('Grick', '2'),
      ('Griffon', '2'),
      ('Guardian Naga', '10'),
      ('Guard Captain', '4'),
      ('Half-Dragon', '5'),
      ('Harpy', '1'),
      ('Hell Hound', '3'),
      ('Hezrou', '8'),
      ('Hill Giant', '5'),
      ('Hippogriff', '1'),
      ('Hippopotamus', '4'),
      ('Hobgoblin Captain', '3'),
      ('Horned Devil', '11'),
      ('Hunter Shark', '2'),
      ('Hydra', '8'),
      ('Ice Devil', '14'),
      ('Imp', '1'),
      ('Incubus', '4'),
      ('Invisible Stalker', '6'),
      ('Iron Golem', '16'),
      ('Killer Whale', '3'),
      ('Knight', '3'),
      ('Kraken', '23'),
      ('Lamia', '4'),
      ('Lich', '21'),
      ('Lion', '1'),
      ('Mage', '6'),
      ('Mammoth', '6'),
      ('Manticore', '3'),
      ('Marilith', '16'),
      ('Medusa', '6'),
      ('Merrow', '2'),
      ('Mimic', '2'),
      ('Minotaur of Baphomet', '3'),
      ('Minotaur Skeleton', '2'),
      ('Mummy', '3'),
      ('Mummy Lord', '15'),
      ('Nalfeshnee', '13'),
      ('Night Hag', '5'),
      ('Nightmare', '3'),
      ('Ochre Jelly', '2'),
      ('Ogre', '2'),
      ('Ogre Zombie', '2'),
      ('Oni', '7'),
      ('Otyugh', '5'),
      ('Owlbear', '3'),
      ('Pegasus', '2'),
      ('Phase Spider', '3'),
      ('Pirate', '1'),
      ('Pirate Captain', '6'),
      ('Pit Fiend', '20'),
      ('Planetar', '16'),
      ('Plesiosaurus', '2'),
      ('Polar Bear', '2'),
      ('Priest', '2'),
      ('Purple Worm', '15'),
      ('Quasit', '1'),
      ('Rakshasa', '13'),
      ('Red Dragon Wyrmling', '4'),
      ('Young Red Dragon', '10'),
      ('Adult Red Dragon', '17'),
      ('Ancient Red Dragon', '24'),
      ('Remorhaz', '11'),
      ('Rhinoceros', '2'),
      ('Roc', '11'),
      ('Roper', '5'),
      ('Saber-Toothed Tiger', '2'),
      ('Salamander', '5'),
      ('Sea Hag', '2'),
      ('Shambling Mound', '5'),
      ('Shield Guardian', '7'),
      ('Silver Dragon Wyrmling', '2'),
      ('Young Silver Dragon', '9'),
      ('Adult Silver Dragon', '16'),
      ('Ancient Silver Dragon', '23'),
      ('Solar', '21'),
      ('Specter', '1'),
      ('Sphinx of Wonder', '1'),
      ('Sphinx of Lore', '11'),
      ('Sphinx of Valor', '17'),
      ('Spirit Naga', '8'),
      ('Spy', '1'),
      ('Stone Giant', '7'),
      ('Stone Golem', '10'),
      ('Storm Giant', '13'),
      ('Succubus', '4'),
      ('Swarm of Piranhas', '1'),
      ('Swarm of Venomous Snakes', '2'),
      ('Tarrasque', '30'),
      ('Tiger', '1'),
      ('Tough Boss', '4'),
      ('Treant', '9'),
      ('Triceratops', '5'),
      ('Troll', '5'),
      ('Tyrannosaurus Rex', '8'),
      ('Unicorn', '5'),
      ('Vampire Familiar', '3'),
      ('Vampire Spawn', '5'),
      ('Vampire', '13'),
      ('Vrock', '6'),
      ('Warrior Veteran', '3'),
      ('Water Elemental', '5'),
      ('Werebear', '5'),
      ('Wereboar', '4'),
      ('Wererat', '2'),
      ('Weretiger', '4'),
      ('Werewolf', '3'),
      ('White Dragon Wyrmling', '2'),
      ('Young White Dragon', '6'),
      ('Adult White Dragon', '13'),
      ('Ancient White Dragon', '20'),
      ('Wight', '3'),
      ('Will-o’-Wisp', '2'),
      ('Winter Wolf', '3'),
      ('Wraith', '5'),
      ('Wyvern', '6'),
      ('Xorn', '5'),
      ('Allosaurus', '2'),
      ('Ankylosaurus', '3'),
      ('Archelon', '4'),
      ('Brown Bear', '1'),
      ('Dire Wolf', '1'),
      ('Elephant', '4');